name: Update HRRR Map
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour on the hour
  workflow_dispatch:      # Allows you to run it manually to test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: sudo apt-get install libeccodes-dev # Needed to decode GRIB2 files

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install herbie-data cartopy matplotlib xarray cfgrib eccodes
          
      - name: Run Script
        run: python update_map.py

      - name: Commit and Push Image
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add latest_hrrr.png
          git commit -m "Update HRRR Map" || exit 0
          git push
